[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
version = "0.0.0"
name = "example-pyproject"

[tool.setuptools]
py-modules = ["example_pyproject"]
include-package-data = false
