[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
version = "0.0.0"
name = "example-pyproject-hatchling"

[tool.hatch.build.targets.wheel]
only-include = ["example_pyproject_hatchling.py"]
